package com.vidnyan.ate.advisor;

import lombok.Builder;
import lombok.Value;
import lombok.extern.jackson.Jacksonized;

import java.util.List;

/**
 * Represents advice generated by the AI Advisor.
 */
@Value
@Builder
@Jacksonized
public class Advice {
    String summary;
    List<Suggestion> suggestions;
    
    @Value
    @Builder
    @Jacksonized
    public static class Suggestion {
        String title;
        String description;
        String impact; // "High", "Medium", "Low"
    }
}
